### ISSUE TITLE
Analytics Results Generatotr

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/daas#4]
This component will be responsible for ingesting the results of analytics processes in an application executed within the Diastema platform and producing the necessary metrics and plots to be visualized within the Visualization framework. Be careful to include components on the most major machine learning algorithms (_**classification, regression, clustering**_).

@konvoulgaris (List from sprint design)
classif metrics: Confusion Matrix, Accuracy, Precision by label, Recall by label, F-measure by label, Weighted precision, Weighted recall, Weighted F-measure
regression metrics: Mean Squared Error (MSE), Root Mean Squared Error (RMSE), Mean Absolute Error (MAE), Coefficient of Determination (R2), Explained Variance
plots/graphs needed IMO: Bar, Column, Line, Area, Stacked Bar, Bubble, scatter plot (sns multi-column scatter plot), Waterfall, 

@yannispoulakis  Suggestions/ Extras
piecharts (mb) , ROC(Classification specific) 
Clustering metrics/graphs ? (Can help with this- YP)
Data Cleaning information? (TBD)

**Comment by konvoulgaris** [comment]
Closing and reopening in analytics-catalogue as its more related there
